### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by LucasHaug** [ThundeRatz/STM32ProjectTemplate#25]
Criando essa issue pra gente fazer uma melhoria depois, acho que dá pra gente tentar fazer a parte de testes de um jeito diferente, poder fazer vários executáveis de teste e escolher qual você vai rodar, ao invés de ter uma única main de teste e ter que ficar alterando ela pra testar coisas separadas diferentes.

**Comment by lucastrschneider** [comment]
Closed by #26
